//
//  DetailsInteractor.swift
//  CleanSwiftArchitectureExample
//
//  Created by Evgeniy Antonov on 7/31/18.
//  Copyright (c) 2018 Evgeniy Antonov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsBusinessLogic
{
  func doSomething(request: Details.Something.Request)
}

protocol DetailsDataStore
{
    var title: String { get set }
}

class DetailsInteractor: DetailsBusinessLogic, DetailsDataStore
{
  var presenter: DetailsPresentationLogic?
  var worker: DetailsWorker?
  var title: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Details.Something.Request)
  {
    worker = DetailsWorker()
    worker?.doSomeWork()
    
    let response = Details.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
