//
//  SearchPresenter.swift
//  CleanSwiftArchitectureExample
//
//  Created by Evgeniy Antonov on 7/26/18.
//  Copyright (c) 2018 Evgeniy Antonov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presentCoctails(response: Search.Coctails.Response)
}

class SearchPresenter: SearchPresentationLogic {
    weak var viewController: SearchDisplayLogic?
    
    // MARK: Do something
    
    func presentCoctails(response: Search.Coctails.Response) {
        let viewModel = Search.Coctails.ViewModel(coctails: response.coctails, isError: response.isError, errorMessage: response.errorMessage)
        if viewModel.isError {
            viewController?.displayError(viewModel: viewModel)
        } else {
            viewController?.displayCoctails(viewModel: viewModel)
        }
    }
}
