//
//  SearchViewController.swift
//  CleanSwiftArchitectureExample
//
//  Created by Evgeniy Antonov on 7/26/18.
//  Copyright (c) 2018 Evgeniy Antonov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SDWebImage

protocol SearchDisplayLogic: class {    
    func displayCocktail(viewModel: Search.RandomCocktail.ViewModel)
    func displayError(viewModel: Search.RandomCocktail.ViewModel)
}

class SearchViewController: UIViewController, SearchDisplayLogic {
    @IBOutlet weak var cocktailTitleLabel: UILabel!
    @IBOutlet weak var cocktailImageView: UIImageView!
    @IBOutlet weak var cocktailInstructionsLabel: UILabel!
    
    var interactor: SearchBusinessLogic?
    var router: (NSObjectProtocol & SearchRoutingLogic & SearchDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        SearchConfigurator.shared.configure(self)
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        loadData()
    }
    
    private func loadData() {
        let request = Search.RandomCocktail.Request()
        interactor?.search(request: request)
    }
    
    // MARK: Display
    
    func displayCocktail(viewModel: Search.RandomCocktail.ViewModel) {
        cocktailTitleLabel.text = viewModel.displayedCocktail?.title
        let url = URL(string: viewModel.displayedCocktail!.thumb)
        cocktailImageView.sd_setImage(with: url)
        cocktailInstructionsLabel.text = viewModel.displayedCocktail?.instructions
    }
    
    func displayError(viewModel: Search.RandomCocktail.ViewModel) {
        print(viewModel.errorMessage ?? "failure")
    }
}
