//
//  SearchModels.swift
//  CleanSwiftArchitectureExample
//
//  Created by Evgeniy Antonov on 7/26/18.
//  Copyright (c) 2018 Evgeniy Antonov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum Search {
    // MARK: Use cases
    
    enum RandomCocktail {
        struct Request {}
        struct Response {
            var cocktail: Cocktail?
            var isError: Bool
            var errorMessage: String?
        }
        struct ViewModel {
            struct DisplayedCocktail {
                var title: String
                var thumb: String
                var instructions: String
            }
            
            var displayedCocktail: DisplayedCocktail?
            var isError: Bool
            var errorMessage: String?
        }
    }
}
