//
//  SearchWorker.swift
//  CleanSwiftArchitectureExample
//
//  Created by Evgeniy Antonov on 7/26/18.
//  Copyright (c) 2018 Evgeniy Antonov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias responseHandler = (_ response: Search.Coctails.Response) ->()

class SearchWorker {
    func fetchCoctails(with searchPhrase: String, success: responseHandler, failure: responseHandler) {
        let manager = APIManager()
        manager.fetchCoctails(with: searchPhrase, success: { (response) in
            let model = Search.Coctails.Response(coctails: response, isError: false, errorMessage: nil)
            success(model);
        }) { (error) in
            let model = Search.Coctails.Response(coctails: nil, isError: true, errorMessage: error.message)
            failure(model);
        }
    }
}
