//
//  SearchPresenter.swift
//  CleanSwiftArchitectureExample
//
//  Created by Evgeniy Antonov on 7/26/18.
//  Copyright (c) 2018 Evgeniy Antonov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presentCoctails(response: Search.RandomCocktail.Response)
}

class SearchPresenter: SearchPresentationLogic {
    weak var viewController: SearchDisplayLogic?
    
    // MARK: Do present
    
    func presentCoctails(response: Search.RandomCocktail.Response) {
        let cocktail = response.cocktail!
        let displayedCocktail = Search.RandomCocktail.ViewModel.DisplayedCocktail(title: cocktail.title, thumb: cocktail.thumb, instructions: cocktail.instructions)
        let viewModel = Search.RandomCocktail.ViewModel(displayedCocktail: displayedCocktail, isError: response.isError, errorMessage: response.errorMessage)
        if viewModel.isError {
            viewController?.displayError(viewModel: viewModel)
        } else {
            viewController?.displayCocktail(viewModel: viewModel)
        }
    }
}
