//
//  SearchModels.swift
//  CleanSwiftArchitectureExample
//
//  Created by Evgeniy Antonov on 7/26/18.
//  Copyright (c) 2018 Evgeniy Antonov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search {
    // MARK: Use cases
    
    enum Coctails {
        struct Request {
            var searchPhrase: String?
        }
        struct Response {
            var coctails: [String]?
            var isError: Bool
            var errorMessage: String?
        }
        struct ViewModel {
            var coctails: [String]?
            var isError: Bool
            var errorMessage: String?
        }
    }
}
